
module.exports = {
  'AdRoll'                   : require('./adroll'),
  'Amplitude'                : require('./amplitude'),
  'BugHerd'                  : require('./bugherd'),
  'Chartbeat'                : require('./chartbeat'),
  'ClickTale'                : require('./clicktale'),
  'Clicky'                   : require('./clicky'),
  'comScore'                 : require('./comscore'),
  'CrazyEgg'                 : require('./crazyegg'),
  'Customer.io'              : require('./customerio'),
  'Errorception'             : require('./errorception'),
  'Evergage'                 : require('./evergage'),
  'FoxMetrics'               : require('./foxmetrics'),
  'Gauges'                   : require('./gauges'),
  'Get Satisfaction'         : require('./get-satisfaction'),
  'Google Analytics'         : require('./google-analytics'),
  'GoSquared'                : require('./gosquared'),
  'Heap'                     : require('./heap'),
  'HitTail'                  : require('./hittail'),
  'HubSpot'                  : require('./hubspot'),
  'Improvely'                : require('./improvely'),
  'Inspectlet'               : require('./inspectlet'),
  'Intercom'                 : require('./intercom'),
  'Keen IO'                  : require('./keen-io'),
  'KISSmetrics'              : require('./kissmetrics'),
  'Klaviyo'                  : require('./klaviyo'),
  'LeadLander'               : require('./leadlander'),
  'LiveChat'                 : require('./livechat'),
  'Lytics'                   : require('./lytics'),
  'Mixpanel'                 : require('./mixpanel'),
  'MouseStats'               : require('./mousestats'),
  'Olark'                    : require('./olark'),
  'Optimizely'               : require('./optimizely'),
  'Perfect Audience'         : require('./perfect-audience'),
  'Pingdom'                  : require('./pingdom'),
  'Preact'                   : require('./preact'),
  'Qualaroo'                 : require('./qualaroo'),
  'Quantcast'                : require('./quantcast'),
  'Sentry'                   : require('./sentry'),
  'SnapEngage'               : require('./snapengage'),
  'Spinnakr'                 : require('./spinnakr'),
  'Tapstream'                : require('./tapstream'),
  'trak.io'                  : require('./trakio'),
  'USERcycle'                : require('./usercycle'),
  'userfox'                  : require('./userfox'),
  'UserVoice'                : require('./uservoice'),
  'Vero'                     : require('./vero'),
  'Visual Website Optimizer' : require('./visual-website-optimizer'),
  'Woopra'                   : require('./woopra')
};