
module.exports = {
  'AdRoll'                   : require('./providers/adroll'),
  'Amplitude'                : require('./providers/amplitude'),
  'BugHerd'                  : require('./providers/bugherd'),
  'Chartbeat'                : require('./providers/chartbeat'),
  'ClickTale'                : require('./providers/clicktale'),
  'Clicky'                   : require('./providers/clicky'),
  'comScore'                 : require('./providers/comscore'),
  'Crazy Egg'                : require('./providers/crazy-egg'),
  'Customer.io'              : require('./providers/customerio'),
  'Errorception'             : require('./providers/errorception'),
  'FoxMetrics'               : require('./providers/foxmetrics'),
  'Gauges'                   : require('./providers/gauges'),
  'Get Satisfaction'         : require('./providers/get-satisfaction'),
  'Google Analytics'         : require('./providers/google-analytics'),
  'GoSquared'                : require('./providers/gosquared'),
  'Heap'                     : require('./providers/heap'),
  'HitTail'                  : require('./providers/hittail'),
  'HubSpot'                  : require('./providers/hubspot'),
  'Improvely'                : require('./providers/improvely'),
  'Inspectlet'               : require('./providers/inspectlet'),
  'Intercom'                 : require('./providers/intercom'),
  'Keen IO'                  : require('./providers/keen-io'),
  'KISSmetrics'              : require('./providers/kissmetrics'),
  'Klaviyo'                  : require('./providers/klaviyo'),
  'LeadLander'               : require('./providers/leadlander'),
  'LiveChat'                 : require('./providers/livechat'),
  'Lytics'                   : require('./providers/lytics'),
  'Mixpanel'                 : require('./providers/mixpanel'),
  'MouseStats'               : require('./providers/mousestats'),
  'Olark'                    : require('./providers/olark'),
  'Optimizely'               : require('./providers/optimizely'),
  'Perfect Audience'         : require('./providers/perfect-audience'),
  'Pingdom'                  : require('./providers/pingdom'),
  'Preact'                   : require('./providers/preact'),
  'Qualaroo'                 : require('./providers/qualaroo'),
  'Quantcast'                : require('./providers/quantcast'),
  'Sentry'                   : require('./providers/sentry'),
  'SnapEngage'               : require('./providers/snapengage'),
  'Spinnakr'                 : require('./providers/spinnakr'),
  'Tapstream'                : require('./providers/tapstream'),
  'trak.io'                  : require('./providers/trakio'),
  'USERcycle'                : require('./providers/usercycle'),
  'userfox'                  : require('./providers/userfox'),
  'UserVoice'                : require('./providers/uservoice'),
  'Vero'                     : require('./providers/vero'),
  'Visual Website Optimizer' : require('./providers/visual-website-optimizer'),
  'Woopra'                   : require('./providers/woopra')
};